### ISSUE TITLE
Error: The Serverless Function "index" is 62.7mb which exceeds the maximum size limit of 50mb.

### ISSUE THREAD

**Issue by alihardan** [dongwa/vercel-quasar#4]
Hello @dongwa and thanks for your nice work. This is the only resource for hosting SSR Quasar at Vercel. I'm using the last version of Quasar, using Vite, and disabled TypeScript. 

I wonder why can't use your builder, Vercel returns:

`Error: The Serverless Function "index" is 62.7mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size`

My project is almost empty of extra assets and packages.

**Comment by dongwa** [comment]
I have created this for my private project and you can find it here: (https://github.com/dongwa/quasar-docs-cn/blob/master/vercel.json). Although I have not yet extensively tested it, I have not encountered any errors. If you could provide more information on how you are using it, as well as more logs of Vercel, I would be happy to help you.

**Comment by alihardan** [comment]
Thank you for your kindness and advice. I don't need to do that right now so I will not bother you. I'll be back whenever I want to do it.
